WIP: use util-lib instead of appStates
reef-defi/reef-react-lib pull request #179
Opened 2023-08-23 14:33 UTC by anukulpandey

- replaced apollo with axios

2023-09-01 08:18 UTC, matjazonline requested changes

2023-09-01 08:18 UTC, matjazonline commented on src/hooks/useInitReefState.ts
> +          accountsSubj.next(loadedReefSigners || []);
accounts in react-lib should be transformed from util-lib observable and not set as Subject - like:
export const injectedSigners$ = reefState.accounts$.pipe(...)
and should be referenced where signers are needed

2023-09-01 08:18 UTC, matjazonline commented on src/hooks/useInitReefState.ts
> +    signers: loadedReefSigners,
loadedReefSigners should then take value from useObservableState(injectedSigners$)

2023-09-12 11:17 UTC, anukulpandey commented
closing this as we will be using https://github.com/reef-defi/reef-react-lib/pull/180

2023-09-12 11:17 UTC, closed without merging